version: '3.8'

networks:
    monitoring:
        driver: bridge

services:
    node_exporter:
        image: prom/node-exporter:latest
        container_name: node_exporter
        volumes:
            - /proc:/host/proc:ro
            - /sys:/host/sys:ro
            - /:/rootfs:ro
        command:
            - '--path.procfs=/host/proc'
            - '--path.rootfs=/rootfs'
            - '--path.sysfs=/host/sys'
            - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
        expose:
            - 9100
        ports:
            - '9100:9100'
        networks:
            - monitoring

    process_exporter:
        image: ncabatoff/process-exporter:latest
        container_name: process_exporter
        privileged: true
        volumes:
            - ./processExporter/conf/process-exporter.yml:/conf/process-exporter.yml
            - /proc:/host/proc:ro
        command:
            - '--config.path=/conf/process-exporter.yml'
            - '--procfs=/host/proc'
        expose:
            - 9256
        ports:
            - '9256:9256'
        networks:
            - monitoring