version: '3.8'

networks:
    monitoring:
        driver: bridge

services:
    prometheus:
        image: prom/prometheus
        container_name: prometheus
        user: "${UserID}"
        volumes:
            - ./prometheus/conf/prometheus.yml:/etc/prometheus/prometheus.yml
            - ./prometheus/data:/prometheus
        expose:
            - 9090
        ports:
            - '9090:9090'
        networks:
            - monitoring
    
    grafana:
        image: grafana/grafana-oss
        container_name: grafana
        user: "${UserID}"
        volumes:
            - ./grafana/data:/var/lib/grafana
            - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources/
            - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards/
        environment:
            - GF_SECURITY_ADMIN_PASSWORD=password
        expose:
            - 3000
        ports:
            - '3000:3000'
        networks:
            - monitoring